/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
module triples.thrift.message.message;

import thrift.base;
import thrift.codegen.base;
import thrift.util.hashset;

import triples.thrift.message.message_types;

interface message {
  void onMessage(string from, string to, string text, string message);

  enum methodMeta = [
    TMethodMeta(`onMessage`,
      [TParamMeta(`from`, -1), TParamMeta(`to`, -2), TParamMeta(`text`, -3), TParamMeta(`message`, -4)]
    )
  ];
}
