/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
module triples.thrift.message.message_types;

import thrift.base;
import thrift.codegen.base;
import thrift.util.hashset;
